### ISSUE TITLE
Tf is this image strech

### ISSUE THREAD

**Issue by Pixie2468** [Dhanam-patel/Landing-Page-with-changable-Background#1]
Solve the problem

**Comment by Dhanam-patel** [comment]
This image stretch issue is something that cannot be solved if i want to use these same ones and even if i change the images or gifs according to your favourable aspect ratio the image is going to be stretch or distorted in the other devices with different aspect ratio. The only way to solve this is custom made images which are created by big brands on their website for devices with every aspect ratio

**Comment by Pixie2468** [comment]
Skill Issue
